name: Deploy modelo ML

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Debug parcial de EC2_KEY (solo para ver encabezado)
        run: |
          echo "Primera línea del EC2_KEY:"
          echo "${{ secrets.EC2_KEY }}" | head -n 1
          echo "Número de líneas totales:"
          echo "${{ secrets.EC2_KEY }}" | wc -l

      - name: Login en DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops-model:dev .

      - name: Conectarse por SSH al EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop mlops-api || true
            docker rm mlops-api || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/mlops-model:dev
            docker run -d -p 8000:8000 --name mlops-api ${{ secrets.DOCKER_USERNAME }}/mlops-model:dev
